### ISSUE TITLE
Infinite potion effects from summoned creepers

### ISSUE THREAD

**Issue by Thyriel** [Yuudaari/soulus#28] opened 2018-02-02 04:14 UTC
Not sure if this is a bug or a feature, but when a creeper explodes while near a player you get the creepers potion effect with endless duration.
This doesn't seem to happen when you kill him or with other mobs

**Comment by Yuudaari** [comment] 2018-02-02 04:29
Well that's amusing. I'll have to consider how I can prevent that. This is caused by a vanilla feature where creepers leave lingering potion area of effects where they explode. I guess the effect duration is based on the duration of the effect on the creeper. 

I guess this isn't *terrible*, because you can drink milk to get rid of the effect if it's negative. I'll probably just reduce the default effect duration on summoned mobs from forever to around five minutes, maybe.

**Comment by Thyriel** [comment] 2018-02-02 06:14
The issue is less that you could get negative effects but more that it's pretty op being able to stack a lot positive effects that way, especially in early game. (and it's a bit annoying having the particles all the time around you).
Reducing the timer seems a good solution to me, that way you can't make much use of the positive effects at all.

Btw somehow it's always when i change summoner.json generating a summoner.err.json that's according to a file comparison tool completely identical.

**Comment by Yuudaari** [comment] 2018-02-02 06:15
Can you send the file that's doing it? I'll see if I can reproduce on my end.

**Comment by Thyriel** [comment] 2018-02-02 06:19
https://pastebin.com/DbgsMsTN
Nothing changed from the default file except duration to 5mins

**Comment by Yuudaari** [comment] 2018-02-02 09:56
There are two checks that happen for a config file to be regenerated:
- The file text needs to be different. In this case, it is different because the order of an object in JSON is not guaranteed. When serializing to JSON, the keys in objects are serialized in "any" order (which usually happens to be the same order, the order just doesn't mean anything... that's why this check fails the first time but passes afterwards)
- The JSON objects internally need to be different. (EG: what was imported, and what was serialized by the mod). This check is broken, however. I didn't write the code that performs this check, which is why it's inconsistent. It probably has some small thing that just so happens to behave strangely in this use case.

I added rewriting the second check to my todo. Once it's consistent, I can remove the first check, because it won't be necessary.

**Comment by Yuudaari** [comment] 2018-02-04 10:10
Fixed as of [v3.2.0](https://github.com/Yuudaari/soulus/releases/tag/v3.2.0)

**Closed by Yuudaari** 2018-02-04 10:10 UTC
Labels: Issue
