### ISSUE TITLE
Crashes on world load

### ISSUE THREAD

**Issue by Pival81** [Yuudaari/soulus#90] opened 2019-11-13 16:47 UTC
https://paste.dimdev.org/acakanodew.rb

Crashes immediately upon world load

**Comment by Yuudaari** [comment] 2019-11-26 05:38
I'm sorry, but I'm unable to reproduce this crash. Some next steps:
1. Can you zip up your Soulus configs and send them? `minecraftfolder/config/soulus`
2. Is this in a pack? Which pack?
3. If this *is* in a pack, and you don't mind, can you send me the save as well? Might be able to reproduce that way.

**Comment by Yuudaari** [comment] 2020-01-24 15:13
Closing because I never received more information. Feel free to give more info at any point and we can re-open this issue!

**Closed by Yuudaari** 2020-01-24 15:13 UTC
Labels: Is: Issue, Kind: Can't Reproduce, Kind: Needs More Info
