### ISSUE TITLE
Game crashed with soulus:summoner

### ISSUE THREAD

**Issue by Lefengisbee** [Yuudaari/soulus#96] opened 2020-01-04 13:05 UTC
Playing soulus mod by using Volcano Block mod pack
Althrough it happened at Atum
But I checked a little bit of crash report
It happened because of summoner
--------Below is crash report-----------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 1/4/20 8:52 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at yuudaari.soulus.common.block.summoner.SummonerTileEntity.spawn(SummonerTileEntity.java:494)
	at yuudaari.soulus.common.block.summoner.SummonerTileEntity.func_73660_a(SummonerTileEntity.java:334)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at yuudaari.soulus.common.block.summoner.SummonerTileEntity.spawn(SummonerTileEntity.java:494)
	at yuudaari.soulus.common.block.summoner.SummonerTileEntity.func_73660_a(SummonerTileEntity.java:334)

-- Block entity being ticked --
Details:
	Name: soulus:summoner // yuudaari.soulus.common.block.summoner.SummonerTileEntity
	Block type: ID #1661 (tile.soulus:summoner // yuudaari.soulus.common.block.summoner.Summoner // soulus:summoner)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-208,65,333), Chunk: (at 0,4,13 in -13,20; contains blocks -208,0,320 to -193,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1661 (tile.soulus:summoner // yuudaari.soulus.common.block.summoner.Summoner // soulus:summoner)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: My world
	All players: 1 total; [EntityPlayerMP['Lefengisbee'/875, l='My world', x=-208.13, y=65.00, z=340.30]]
	Chunk stats: ServerChunkCache: 272 Drop: 0
	Level seed: 7008437886868531220
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 468856216 bytes (447 MB) / 1754267648 bytes (1673 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 60
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 140 mods loaded, 140 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version              | Source                                                | Signature                                |
	|:------ |:------------------------- |:-------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2               | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                       | 9.42                 | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                       | 8.0.99.99            | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCHIJA | forge                     | 14.23.5.2847         | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCHIJA | foamfixcore               | 7.7.4                | minecraft.jar                                         | None                                     |
	| LCHIJA | rpghud                    | 3.6.6.2              | [1.12] RPG-HUD-3.6.6.2.jar                            | None                                     |
	| LCHIJA | deconstruction            | 3.0.4                | [MC1.12.2]DeconTable-3.0.4.jar                        | None                                     |
	| LCHIJA | forgelin                  | 1.8.4                | Forgelin-1.8.4.jar                                    | None                                     |
	| LCHIJA | alib                      | 1.0.12               | alib-1.0.12.jar                                       | None                                     |
	| LCHIJA | crafttweaker              | 4.1.20               | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
	| LCHIJA | alchemistry               | 1.0.36               | alchemistry-1.0.36.jar                                | None                                     |
	| LCHIJA | applecore                 | 3.2.0                | AppleCore-mc1.12.2-3.2.0.jar                          | None                                     |
	| LCHIJA | mtlib                     | 3.0.6                | MTLib-3.0.6.jar                                       | None                                     |
	| LCHIJA | modtweaker                | 4.0.17               | modtweaker-4.0.17.jar                                 | None                                     |
	| LCHIJA | jei                       | 4.15.0.292           | jei_1.12.2-4.15.0.292.jar                             | None                                     |
	| LCHIJA | appleskin                 | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                            | None                                     |
	| LCHIJA | architecturecraft         | @VERSION@            | architecturecraft-1.12-3.98.jar                       | None                                     |
	| LCHIJA | athenaeum                 | 1.12.2-1.17.4        | athenaeum-1.12.2-1.17.4.jar                           | None                                     |
	| LCHIJA | baubles                   | 1.5.2                | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCHIJA | atum                      | 2.0.16               | Atum-1.12.2-2.0.16.jar                                | None                                     |
	| LCHIJA | badwithernocookiereloaded | 1.12.2-3.3.16        | badwithernocookiereloaded-1.12.2-3.3.16.jar           | None                                     |
	| LCHIJA | bdsandm                   | 0.0.24               | BarrelsDrumsStorageAndMore-0.0.24.jar                 | None                                     |
	| LCHIJA | base                      | 3.13.0               | base-1.12.2-3.13.0.jar                                | None                                     |
	| LCHIJA | betteradvancements        | 0.1.0.77             | BetterAdvancements-1.12.2-0.1.0.77.jar                | None                                     |
	| LCHIJA | betterbuilderswands       | 0.13.2               | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar     | None                                     |
	| LCHIJA | blockdrops                | 1.4.0                | blockdrops-1.12.2-1.4.0.jar                           | None                                     |
	| LCHIJA | bnbgaminglib              | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                        | None                                     |
	| LCHIJA | bookshelf                 | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania                   | r1.10-362            | Botania r1.10-362.jar                                 | None                                     |
	| LCHIJA | bowinfinityfix            | rv5.1                | BowInfinityFix-1.12.2-rv5.1.jar                       | None                                     |
	| LCHIJA | buildinggadgets           | 2.7.4                | BuildingGadgets-2.7.4.jar                             | None                                     |
	| LCHIJA | sonarcore                 | 5.0.19               | sonarcore-1.12.2-5.0.19-20.jar                        | None                                     |
	| LCHIJA | calculator                | 5.0.11               | calculator-1.12.2-5.0.11-12.jar                       | None                                     |
	| LCHIJA | cannibalism               | 5.6.3                | Cannibalism-5.6.3-1.12.2.jar                          | None                                     |
	| LCHIJA | carryon                   | 1.12.3               | CarryOn MC1.12.2 v1.12.3.jar                          | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | chameleon                 | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                              | None                                     |
	| LCHIJA | chiselsandbits            | 14.33                | chiselsandbits-14.33.jar                              | None                                     |
	| LCHIJA | clumps                    | 3.1.2                | Clumps-3.1.2.jar                                      | None                                     |
	| LCHIJA | combustfish               | 1.0.3.4              | combustfish-1.12.2-1.0.3.4.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | cyclopscore               | 1.6.0                | CyclopsCore-1.12.2-1.6.0.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | commoncapabilities        | 2.4.5                | CommonCapabilities-1.12.2-2.4.5.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | compactstorage            | 3.1                  | CompactStorage-3.1-12.jar                             | None                                     |
	| LCHIJA | compatched                | 1.6.0                | ComPatchedStorage-1.12.2-1.6.0.jar                    | None                                     |
	| LCHIJA | contenttweaker            | 1.12.2-4.9.1         | ContentTweaker-1.12.2-4.9.1.jar                       | None                                     |
	| LCHIJA | controlling               | 3.0.7                | Controlling-3.0.7.jar                                 | None                                     |
	| LCHIJA | craftingstation           | @VERSION@            | craftingstation-0.1.7b.jar                            | None                                     |
	| LCHIJA | craftingtweaks            | 8.1.9                | CraftingTweaks_1.12.2-8.1.9.jar                       | None                                     |
	| LCHIJA | ctgui                     | 1.0.0                | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
	| LCHIJA | crafttweakerjei           | 2.0.3                | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
	| LCHIJA | cropdusting               | 0.7                  | CropDusting-0.7-[1.12.2].jar                          | None                                     |
	| LCHIJA | ctm                       | MC1.12.2-1.0.1.30    | CTM-MC1.12.2-1.0.1.30.jar                             | None                                     |
	| LCHIJA | custommainmenu            | 2.0.9                | CustomMainMenu-MC1.12.2-2.0.9.jar                     | None                                     |
	| LCHIJA | darkutils                 | 1.8.230              | DarkUtils-1.12.2-1.8.230.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ding                      | 1.0.2                | Ding-1.12.2-1.0.2.jar                                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | discordcraft              | 1.0                  | DiscordCraft-1.0.3.1.jar                              | None                                     |
	| LCHIJA | dropt                     | 1.12.2-1.16.1        | dropt-1.12.2-1.16.1.jar                               | None                                     |
	| LCHIJA | emberroot                 | 1.3.9                | EmberRootZoo-1.12.2-1.3.10.jar                        | None                                     |
	| LCHIJA | embers                    | 1.13-hotfix2         | EmbersRekindled-1.13-hotfix2.jar                      | None                                     |
	| LCHIJA | embersified               | 1.0.3                | Embersified-1.12.2-1.0.3.jar                          | None                                     |
	| LCHIJA | evilcraft                 | 0.10.78              | EvilCraft-1.12.2-0.10.78.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | evilcraftcompat           | 1.0.0                | EvilCraft-1.12.2-0.10.78.jar                          | None                                     |
	| LCHIJA | fastleafdecay             | v14                  | FastLeafDecay-v14.jar                                 | None                                     |
	| LCHIJA | fencejumper               | 1.0.5                | fencejumper-1.12-1.0.5.jar                            | None                                     |
	| LCHIJA | flopper                   | 1.0.3                | Flopper-1.12.2-1.0.3.jar                              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | foamfix                   | 0.10.9-1.12.2        | foamfix-0.10.9-1.12.2.jar                             | None                                     |
	| LCHIJA | forbidden_arcanus         | 1.12.2-1.1.4         | forbidden_arcanus-1.12.2-1.1.4.jar                    | None                                     |
	| LCHIJA | ftbbackups                | 1.1.0.1              | FTBBackups-1.1.0.1.jar                                | None                                     |
	| LCHIJA | ftblib                    | 5.4.4.5              | FTBLib-5.4.4.5.jar                                    | None                                     |
	| LCHIJA | ftbutilities              | 5.4.0.124            | FTBUtilities-5.4.0.124.jar                            | None                                     |
	| LCHIJA | itemfilters               | 1.0.3.12             | ItemFilters-1.0.3.12.jar                              | None                                     |
	| LCHIJA | ftbquests                 | 1.8.0.237            | FTBQuests-1.8.0.237.jar                               | None                                     |
	| LCHIJA | fxcontrol                 | 0.1.14               | fxcontrol-1.12-0.1.14.jar                             | None                                     |
	| LCHIJA | globalgamerules           | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar                      | None                                     |
	| LCHIJA | harvest                   | 1.12-1.2.7-20        | Harvest-1.12-1.2.7-20.jar                             | None                                     |
	| LCHIJA | hwell                     | 0.4.2                | hwell-0.4.2.jar                                       | None                                     |
	| LCHIJA | ichunutil                 | 7.2.2                | iChunUtil-1.12.2-7.2.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | incontrol                 | 3.9.16               | incontrol-1.12-3.9.16.jar                             | None                                     |
	| LCHIJA | initialinventory          | 2.0.2                | InitialInventory-3.0.0.jar                            | None                                     |
	| LCHIJA | mantle                    | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LCHIJA | inspirations              | 1.12.2-0.2.8         | Inspirations-1.12.2-0.2.8.jar                         | None                                     |
	| LCHIJA | integrateddynamics        | 1.1.1                | IntegratedDynamics-1.12.2-1.1.1.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integrateddynamicscompat  | 1.0.0                | IntegratedDynamics-1.12.2-1.1.1.jar                   | None                                     |
	| LCHIJA | integratedterminals       | 1.0.13               | IntegratedTerminals-1.12.2-1.0.13.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integratedterminalscompat | 1.0.0                | IntegratedTerminals-1.12.2-1.0.13.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integratedtunnels         | 1.6.10               | IntegratedTunnels-1.12.2-1.6.10.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | integratedtunnelscompat   | 1.0.0                | IntegratedTunnels-1.12.2-1.6.10.jar                   | None                                     |
	| LCHIJA | inventorytweaks           | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | inworldcrafting           | 1.12.2-1.2.0         | inworldcrafting-1.12.2-1.2.0-universal.jar            | None                                     |
	| LCHIJA | itlt                      | 1.0.0                | itlt-1.12.2-1.0.2.jar                                 | None                                     |
	| LCHIJA | jeiintegration            | 1.5.1.36             | jeiintegration_1.12.2-1.5.1.36.jar                    | None                                     |
	| LCHIJA | jetif                     | 1.5.1                | jetif-1.12.2-1.5.1.jar                                | None                                     |
	| LCHIJA | journeymap                | 1.12.2-5.5.6b1       | journeymap-1.12.2-5.5.6b1.jar                         | None                                     |
	| LCHIJA | loottweaker               | 0.0.10               | LootTweaker-1.12.2-0.0.10.jar                         | None                                     |
	| LCHIJA | jeresources               | 0.9.2.60             | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
	| LCHIJA | laggoggles                | FAT-1.12.2-4.9       | LagGoggles-FAT-1.12.2-4.9.jar                         | None                                     |
	| LCHIJA | reborncore                | 3.16.4.478           | RebornCore-1.12.2-3.16.4.478-universal.jar            | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | mainmenuscale             | 1.0                  | MainMenuScale-1.3.2.jar                               | None                                     |
	| LCHIJA | mobamputation             | 7.0.0                | MobAmputation-1.12.2-7.0.0.jar                        | None                                     |
	| LCHIJA | mobdismemberment          | 7.0.0                | MobDismemberment-1.12.2-7.0.0.jar                     | None                                     |
	| LCHIJA | modnametooltip            | 1.10.1               | modnametooltip_1.12.2-1.10.1.jar                      | None                                     |
	| LCHIJA | morecharcoal              | 1.12.2-1.0.9         | morecharcoal-1.12.2-1.0.9.jar                         | None                                     |
	| LCHIJA | moreoverlays              | 1.15.1               | moreoverlays-1.15.1-mc1.12.2.jar                      | None                                     |
	| LCHIJA | mousetweaks               | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                         | None                                     |
	| LCHIJA | netherchest               | 1.1.1                | netherchest-1.1.1.jar                                 | None                                     |
	| LCHIJA | norecipebook              | 1.2.1                | noRecipeBook_v1.2.2formc1.12.2.jar                    | None                                     |
	| LCHIJA | offlineskins              | 1.12.2-v6            | OfflineSkins-Mod-1.12.2.jar                           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | oreexcavation             | 1.4.143              | OreExcavation-1.4.143.jar                             | None                                     |
	| LCHIJA | patchouli                 | 1.0-20               | Patchouli-1.0-20.jar                                  | None                                     |
	| LCHIJA | placebo                   | 1.6.0                | Placebo-1.12.2-1.6.0.jar                              | None                                     |
	| LCHIJA | prodigytech               | 1.3.4                | prodigytech-1.12.2-1.3.4.jar                          | None                                     |
	| LCHIJA | resourceloader            | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | rsgauges                  | 1.1.10-b2            | rsgauges-1.12.2-1.1.10-b2.jar                         | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | seeddrop                  | 1.2.1-1.12           | SeedDrop-1.2.1-1.12.jar                               | None                                     |
	| LCHIJA | simpleflax                | 1.2.1                | SimpleFlax-1.2.1.jar                                  | None                                     |
	| LCHIJA | simple_trophies           | 1.2.1                | simpletrophies-1.2.1.jar                              | None                                     |
	| LCHIJA | soulus                    | 1.12.2-4.3.3-f3404c1 | Soulus-1.12.2-4.3.3-f3404c1.jar                       | None                                     |
	| LCHIJA | speedyhoppers             | 1.1.19               | speedyhoppers-1.1.19.jar                              | None                                     |
	| LCHIJA | speedyladders             | 1.1.3                | speedyladders-1.1.3.jar                               | None                                     |
	| LCHIJA | stonechest                | 1.0.4                | StoneChest-1.0.4.jar                                  | None                                     |
	| LCHIJA | storagedrawers            | 1.12.2-5.4.0         | StorageDrawers-1.12.2-5.4.0.jar                       | None                                     |
	| LCHIJA | strawgolem                | 1.3                  | strawgolem-1.4.1.jar                                  | None                                     |
	| LCHIJA | structuredcrafting        | 0.2.1                | StructuredCrafting-1.12.2-0.2.1.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | theoneprobe               | 1.4.28               | theoneprobe-1.12-1.4.28.jar                           | None                                     |
	| LCHIJA | telepastries              | 0.3.4                | TelePastries-0.3.4.jar                                | None                                     |
	| LCHIJA | tetra                     | 0.39.1               | tetra-1.12.2-0.39.1.jar                               | None                                     |
	| LCHIJA | toastcontrol              | 1.8.1                | Toast Control-1.12.2-1.8.1.jar                        | None                                     |
	| LCHIJA | topography                | 1.10.1               | Topography-1.12.2-1.10.1.jar                          | None                                     |
	| LCHIJA | tramplestopper            | 1.2.0.4              | tramplestopper-1.12.2-1.2.0.5-universal.jar           | None                                     |
	| LCHIJA | trashslot                 | 8.4.10               | TrashSlot_1.12.2-8.4.10.jar                           | None                                     |
	| LCHIJA | uniquecrops               | 0.1.76               | uniquecrops-1.12-0.1.76.jar                           | None                                     |
	| LCHIJA | usefulnullifiers          | 1.5.0                | usefulnullifiers-1.5.0.jar                            | None                                     |
	| LCHIJA | vanillafoodpantry         | 4.3.1                | vanillafoodpantry-mc1.12.2-4.3.1.jar                  | None                                     |
	| LCHIJA | vaultopic                 | 2.1                  | vaultopic-2.1.jar                                     | None                                     |
	| LCHIJA | vefluids                  | 0.11.0.17            | VE-FluidHandling-1.12.2-0.11.0b17.jar                 | None                                     |
	| LCHIJA | volcanoblocktweaks        | 1.0.0                | volcanoblocktweaks-1.0.0.jar                          | None                                     |
	| LCHIJA | woodenbucket              | 0.3.0.22             | WoodenBuckets-1.12.2-0.3.0b22.jar                     | None                                     |
	| LCHIJA | worldedit                 | 6.1.10-SNAPSHOT      | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (2).jar | None                                     |
	| LCHIJA | xencraft                  | 1.0.0.4              | XenCraft-1.0.0.4.jar                                  | None                                     |
	| LCHIJA | reauth                    | 3.6.0                | reauth-3.6.0.jar                                      | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCHIJA | solcarrot                 | 1.8.3                | solcarrot-1.12.2-1.8.3.jar                            | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  lain.mods.skins.init.forge.asm.ASMTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- TheOneProbePlugin (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.4.478
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['My-ID'/875, l='My world', x=-208.13, y=65.00, z=340.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Yuudaari** [comment] 2020-01-04 13:34
Duplicate of #94

**Closed by Yuudaari** 2020-01-04 13:34 UTC
Labels: Kind: Duplicate
